# mode: "upstream:http://host.docker.internal:1082"
anticache: True
ssl_insecure: True
block_global: False
with_dumper: True
listen_host: "0.0.0.0"
listen_port: 10800
web_port: 10801
# onboarding_port: 80

# hardump: "./hardump/testdump.har"
scripts: [
    "mitmproxy/addons/defy/defyurlredirect.py",
    "mitmproxy/addons/defy/defyrewrite.py",
    "mitmproxy/addons/defy/shutdown.py",
    # "mitmproxy/addons/defymapremote_standalone.py",
    # "mitmproxy/addons/defymaplocal_standalone.py",
    # "mitmproxy/addons/browserup/browserup_addons_manager.py",
    # '~/mitmproxy-addons/offline.py',
    # "examples/addons/shutdown.py",
    # '~/mitmproxy-addons/sleeper.py'
  ]