anticache: true
block_global: false
listen_host: 0.0.0.0
mode: upstream:http://host.docker.internal:1082
scripts:
- mitmproxy/addons/defy/defyurlredirect.py
- mitmproxy/addons/defy/defyrewrite.py
ssl_insecure: true
with_dumper: true
